services:
  - type: web
    name: discord-license-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: KEY_PREFIX
        value: ADAMCORP
      - key: KEY_LENGTH
        value: "5"
      - key: REQUIRED_ROLE_NAME
        value: Reseller
      - key: PORT
        value: "8080"
